### ISSUE TITLE
Focus out of the month box doesn't work through mouse click on a touch screen laptop. 

### ISSUE THREAD

**Issue by ronaksvyas** [nickeljew/react-month-picker#10]
I implemented this plugin and it works fine normally. 

One strange issue I found with this is when I select two months and want to close the month picker, anyone would do it by clicking somewhere else on the screen which makes this component lose focus. Clicking through mouse or touchpad doesn't work in a touch screen laptop and it remains open when I click anywhere. When I touch the screen for that mouse click, the plugin recognizes the even and it gets closed. Could you guys please look into this as this will affect the touch screen users. 

This is happening on a Dell Touchscreen laptop on Chrome browser.

**Comment by nickeljew** [comment]
Oh, yes. The issue caused by my another component react-tapper used in react-month-picker. I disabled click event handler to be triggered on touch-support device to prevent multiple triggering with touch event and click event at the same time by browser on some devices. There might be other way to do that instead of simply disabling click handler. I will improve it a little later.

**Comment by ronaksvyas** [comment]
@nickeljew: Thank you for your prompt response. It would be great if this is fixed in future releases.
