### ISSUE TITLE
Using the class .show in the .month-picker .container

### ISSUE THREAD

**Issue by Fettabachi** [nickeljew/react-month-picker#24]
Bootstrap also uses `.show` but but they add the `!important` modifier to it which ruins the sliding animation of the container. Maybe you could alter it to something more specific to the component like .show-calendar.

Thanks for sharing this excellent component.

**Comment by Fettabachi** [comment]
I see now. I add `display:table!important;` to over-ride bootstrap.

**Comment by nickeljew** [comment]
To be honest, with my opinion, Bootstrap's naming style is obsolete can always causing naming pollution. Instead, hierarchical naming is the proper way. Moreover, abuse of !important is flooding in Bootstrap.
That's why I don't like Bootstrap and did nothing to care about its naming pollution.

Sorry for you have to deal with the conflict. BTW, if you really like to use Bootstrap, you may search another library forked from my react-month-picker with modification of class names for avoiding the conflict with Bootstrap.
