### ISSUE TITLE
Picker class names interfere with other classes

### ISSUE THREAD

**Issue by MudriyK** [nickeljew/react-month-picker#27]
Picker CSS classes have commonly used names and thus interfere with other styles. Consider replacing commonly used class names like '.table', '.popup', '.btn' etc. with more specific names (for example 'react_month_picker-popup')

**Comment by nickeljew** [comment]
If you are using cascading naming, there will not be any issue.

Yes, I know there are conflicts when using bootstrap, but that's the problem of bootstrap's famous naming pollution. Moreover, it's not a good habit to using very common naming in global, and the better solution is to cascade the naming to restrict the scoping.

**Comment by MudriyK** [comment]
I agree, but sometimes we use need global naming for reusable components on big projects, such as 'popup', 'table', which apply general CSS for the whole project and thus cannot be cascaded. My opinion is that in case of a separate module, class names can be adjusted and specified much easier than for the whole project.

**Comment by nickeljew** [comment]
In my opinion, on the contrary, it's better to use specific css class names in global instead of common names, and common names will be free to use in cascading. That will avoid naming restriction or pollution for development of components or partial pages.

However, I gave up the insistence of naming principle in this component for saving time for everyone. Please check v1.3.5 to get that update.
