### ISSUE TITLE
Don't reset current year on empty range

### ISSUE THREAD

**Issue by MaartenAerts** [nickeljew/react-month-picker#35]
When I select a month, then deselect the month the calendar automatically changes to the current year. I would like it to stay in the same year as it was. This is because of the validate method not finding the current selected month and defaulting to the current year.

You have any advice on how to proceed? Should I just fork your repository? Should I create a pull request with a flag to switch to this behavior?

**Comment by nickeljew** [comment]
What do you mean 'deselect the month'?
The component does not support 'deselect' operation, so I'm not quit clear about your issue.

**Comment by MaartenAerts** [comment]
Yes the deselecting logic is outside of your component. 

Given there is a range provided for range in a year other than the current year.
When the range is now cleared to empty objects.
Then the component switches to showing the current year.

I would like it to stay the same year that was shown previously.
The year switches to the current year because of lines 157-174.

Is it clearer this way?

**Comment by nickeljew** [comment]
If you 'deselect the month', suggest keeping the previous value of Prop value or Prop range. If the prop stays the same, the issue you mentioned will not happen.

I believe that issue happens when you 'deselect the month', and the Prop value or Prop has also changed (without correct reset), and lost some critical data, so the validate method has to fall back to a 'default' year value.

**Comment by MaartenAerts** [comment]
I don't quite understand your solution. If I keep the range prop the same, I have effectively not cleared it and my use case is clearing it.

The user needs to be able to select a month, click it again to not have any month selected and then click another month. During this action I don't want the validate method to switch the current year.

This needs to be possible because the years prop also changes depending on the selected range to limit the user the range he can select. When there is no range the years prop allows the user to select anywhere. When the user has a from or to selected he is limited to a couple of months.

**Comment by nickeljew** [comment]
The component does not support “no month selected”. A selected month is
required.

However, the purpose of the component is to let user to pick a month. If
your application allows user to ignore month selection, it’s not
complicated to fulfill it. The month choice displaying box is all your
work. You can implement a flag in your displaying box to indicate if a
month is picked. If not, the flag is
set as false, and the displaying box show empty value. Otherwise, if yes,
the flag is true and the box shows the picked month. Moreover, no matter
the flag is true or false, the Prop value (or Prop range) of
react-month-picker can not be empty, but it is unnecessary to let user be
aware of that.

**Comment by MaartenAerts** [comment]
But the user sees a highlighted month in the month picker which is very confusing. I understand it is not supported. If I want to support it I shall just fork the repository?

**Comment by nickeljew** [comment]
Fork or not is up to you. It’s not my concern.

I don’t think a default picked month is an issue, but that’s your
requirement, and I have no right to judge.

The only last thing I can make it clearer. The component does not allow
empty choice. Do what ever you want to do to meet your needs.

**Comment by MaartenAerts** [comment]
Ok thank you so much for your help and interactivity.
