### ISSUE TITLE
 css not used 

### ISSUE THREAD

**Issue by coolpopo** [nickeljew/react-month-picker#38]
the css is not being used on a fresh npm install of this package. I've had to manually copy and paste the css and import it into my component

**Comment by nickeljew** [comment]
Yes, I meant to make user to import the css/scss into his project manually. The component is not using some kind of css-in-js styling scheme. My intent is to keep css independency, and user may be free to override parts of the styles or just rewrite the whole component styling.

In my own projects, the component's scss file is imported from nodemodules path as following:
```
@import 'node_modules/react-picker/scss/picker';
```

**Comment by simonarcher** [comment]
When I did a fresh install of the project on a new pc and did a build, my picker now looks like this..

is this because of the problem discussed in this issue?

Im not exactly clear how to resolve it.. where do I put that line which imports the CSS?

Thanks!

<img width="390" alt="screenshot 2018-12-01 at 12 21 06" src="https://user-images.githubusercontent.com/10696147/49327134-ce831800-f565-11e8-92f2-7aa04cc19332.png">

**Comment by nickeljew** [comment]
If you are using scss, please make sure import the component's scss file. If not, you may need to copy those css codes into your file.
I don't like css-in-js, so keep the css outside jsx codes.
