### ISSUE TITLE
Push new version with fixes?

### ISSUE THREAD

**Issue by bibodha** [nickeljew/react-month-picker#6]
Will you push a new version to npm with the new commits? The last push to npm was February 25, 2016. 

Thank you.

**Comment by abhaytalreja** [comment]
Also, when installing the library from npm, we get the below issue. It will be great if you can fix the version of the peer-dependencies.
```
├── UNMET PEER DEPENDENCY react@15.0.2
└─┬ react-month-picker@1.0.8 
  ├── UNMET PEER DEPENDENCY react@^0.14.3
  └── react-tapper@0.1.5 
```

**Comment by nickeljew** [comment]
Just update a version with peer dependency on latest react (v15.1.0)

**Comment by severisv** [comment]
react-month-picker 1.0.10 is not compatible with react 15.1.0.

In our project we had required month-picker with ^10.0.8, so we found out the hard way.

**Comment by alee8** [comment]
Can confirm what severlsw says.  Right now there is no version of the latest code that works with React 15.x that I could determine.  Chrome complains 'cannot read property createClass (month-picker.js: 78) of undefined.

I got:
react-month-picker 1.0.3
react-tapper 0.1.3 
to work with react 0.14.x but this lacks many of the recent fixes.

**Comment by nickeljew** [comment]
I'm using react v15.1.0 and react-month-picker v1.0.10 in my project, and it works fine. Can I ask what exactly error shown in your browser, @severisv ?

----
@alee8  line 70 in lib/month-picker.js:
var MonthPicker = _react2.default.createClass({...

The relevant code line in original JSX file:
let MonthPicker = React.createClass({..

If you include react.js in your project correctly, I don't think there will be a problem here. Actually, you can see the example page of react-month-picker works fine also.

----------
Or can you give more specific details of the problem?

**Comment by alee8** [comment]
I tried something more basic.  I pulled a copy of the code.  
I did a 'npm install' and this is what I got at the end of this.
npm WARN react-month-picker@1.0.10 requires a peer of react@^15.1.0 but none was installed.
npm WARN react-month-picker@1.0.10 requires a peer of react-dom@^15.1.0 but none was installed.
npm WARN react-tapper@0.1.8 requires a peer of react@^15.1.0 but none was installed.

**Comment by nickeljew** [comment]
Are you using npm@2.x or lower version?  
You can use npm@3.x which doesn’t warn your to require packages as peer dependencies.
OR, you may install react@15.1.0 & react-dom@15.1.0 by yourself with npm to stop the warning.

**Comment by alee8** [comment]
When I ran npm, it was version 3.8.8.

I can install react@15.1.0, and react-dom@15.1.0 in the source directory. How would you suggest running react-month-picker standalone (say your example)? This was what I was aiming for when I downloaded and did the npm install.

When I included react-month-picker in my React app, I needed to add browserify-shim (v3.8.12) because it was not installed.  Other than that, I just included react-month-picker.  Note, I referenced month-picker.js:78 because my react app loaded lib/month-picker.js via require('react-month-picker"').default  My react app uses babelify and react-month-picker uses browserify-shim (any potential of conflict?).

**Comment by nickeljew** [comment]
@alee8 
no no no, react-month-picker does not require browserify-shim, and it's optional. Besides, I do not use browserify-shim either, and there is no warning for browserify-shim when I install the package by npm.

React-month-picker is compiled by babel, not browserify. It's not wrong if you load the component via requires('...').default, and I tried it too.

Can I ask how you include react and react-dom into your app? I don't know if there is any issue here, just ask, since I tried everything you mentioned before, and all work fine.

The error you listed, "cannot read property createClass (month-picker.js: 78) of undefined", apparently, refers to your React component not loaded correctly.

Just FYI:
In my app, I usually load react components via es6 syntax 'import', but 'require' syntax also works, and load react & react-dom in separate files instead of packing all stuff into one file. Then, I pack the app.js with webpack. Since react & react-dom are external components in my app, my webpack config must include a setting a following:
```
    ...
    ,externals: {
        'react': 'React'
        , 'react-dom': 'ReactDOM'
    }
   ...
```

**Comment by nickeljew** [comment]
@alee8 
I figured out one.
Yes, if you include react-month-picker in dependencies or devDependencies of your project, you have to include react & react-dom in dependencies or devDependencies too, or install them manually, coz react-month-picker requires a peer dependency on react & react-dom.

BUT, it's not the cause for the error you mentioned ('cannot read property createClass (month-picker.js: 78) of undefined'). That error is caused by loading react & react-dom unsuccessfully.

**Comment by severisv** [comment]
I have the same error ('cannot read property createClass of undefined').

package.json: 
"dependencies": {
     .......
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-month-picker": "1.0.10",
  },

We are build our bundle with browserify and we are also running babel with presets: ["es2015", "react"] and plugins: ["transform-object-rest-spread", "jsx-control-statements"].

We have separate bundles for our libraries and our own code, and react-month-picker is not in the same bundle as react and react-dom, which might be the cause. I will try to put them in the same bundle and see if it helps, but I don't have time to verify right now. 

Our setup works with react 15 and month-picker 1.0.8.

**Comment by nickeljew** [comment]
@severisv 
I haven't used browserify before. That patch in package.json for browserify came from @bcherny.
The patch configuration as following:
```
"browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "react": "global:React"
  },
```
But the patch wasn't published to npm until 1.0.10.
I wonder if there is any conflict configuration here with yours. If there is, please notify me.

**Comment by severisv** [comment]
We are using browserify-shim, but we haven't shimmed React, and we don't see a good reason to do it either.

This is our setup:
[gulp js](https://gist.github.com/severisv/e8d04e588331aa19f07c268d251095f3)
[package.json](https://gist.github.com/severisv/35d7973f38af85785f5d4c929d1ff539)

**Comment by alee8** [comment]
Sorry to disappear from the grid.  Had something else that was more pressing to deal with.
Now that I return to this, I can add:
a) My app that includes your component does not build bundles.
b) My app includes your component in my package.json's dependencies.
c) My app included react and react-dom in my package.json's dependencies
d) My app uses browserify with babelify transform.  Your component has browserify-shim which may clash with my app's browserify transform.  As detailed above, I have to add browserify-shim my package.json's dependencies; otherwise the app does not load.
e) As indicated above, the only version that will work with react 0.14.x is react-month-picker@1.0.3 with react-tapper@0.1.3.  I have tried to switch my app to react 15.1.0 and include 1.0.8/1.0.10 and get error 'Uncaught TypeError: Cannot read property 'createClass' of undefined'.

If you can produce a version 1.1.0 that does not have the following, I can try to see if the react 15.1.0 version of my app can use this 1.1.0 of your component.  
"browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "react": "global:React"
  },
 
It also appears that the versioning of react-tapper is not properly sync'ed with react-month-picker so that my react 0.14.x can use an earlier version of react-month-picker (but later than 1.0.3) without the browserify-shim add-ins.

Let me know if you would be willing to explore a 1.1.0 version (matched properly with react-tapper version) for use with react 15.1.0 app.

**Comment by nickeljew** [comment]
@alee8 removed browserify-shim configuration from package.json and publish v1.0.11. Please test it.

Next time I will test it before merging.

**Comment by alee8** [comment]
Would be happy to try it once it publishes?  Don't see it yet.

**Comment by bcherny** [comment]
This is my bad -- sorry it took so long to comment. @nickeljew please roll back my PR https://github.com/nickeljew/react-month-picker/commit/7b38d6bc3622b7f91183f208dc30cb4788838bfb.

I was trying to get React-Month-Picker working with a CDN'd React. However, the code in that PR prevents React-Month-Picker from working with a non-CDN'd React if the project uses browserify-shim!

The fix is to revert that commit and publish a new version.

I also made a demo repo for anyone that wants to get React-Month-Picker working with CDN'd (or non-CDN'd React) with browserify in the future: https://github.com/bcherny/react-month-picker-demo/blob/master/package.json.

**Comment by alee8** [comment]
I can confirm that v1.0.11 works correctly.
